# Databricks notebook source
# COMMAND ----------
# ==============================
# CONFIG
# ==============================
zip_source_path = "abfss://bronze@stspmobilitydev001.dfs.core.windows.net/gtfs/raw/cittamobi_gtfs.zip"
zip_local_path = "/tmp/cittamobi_gtfs.zip"

{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "144bc3b2-c7c8-41bb-b630-0f33157e78d6",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "# Databricks notebook source\n",
    "# COMMAND ----------\n",
    "\n",
    "# COMMAND ----------\n",
    "from datetime import datetime\n",
    "from pyspark.sql.functions import current_timestamp, input_file_name, lit\n",
    "import os\n",
    "import shutil\n",
    "import zipfile\n",
    "\n",
    "# COMMAND ----------\n",
    "# Parâmetros\n",
    "storage_account = \"stspmobilitydev001\"\n",
    "container = \"bronze\"\n",
    "\n",
    "ingestion_date = datetime.now().strftime(\"%Y-%m-%d\")\n",
    "run_id = datetime.now().strftime(\"%Y%m%d%H%M%S\")\n",
    "\n",
    "raw_base_path = f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs\"\n",
    "\n",
    "# Caminhos candidatos para o ZIP GTFS\n",
    "zip_candidate_paths = [\n",
    "    f\"{raw_base_path}/raw/cittamobi_gtfs.zip\",\n",
    "    f\"{raw_base_path}/cittamobi_gtfs.zip\",\n",
    "    f\"abfss://{container}@{storage_account}.dfs.core.windows.net/raw/gtfs/cittamobi_gtfs.zip\",\n",
    "    f\"abfss://{container}@{storage_account}.dfs.core.windows.net/cittamobi_gtfs.zip\",\n",
    "]\n",
    "\n",
    "extract_base_local = f\"/tmp/gtfs_extract_{run_id}\"\n",
    "zip_local_path = f\"/tmp/cittamobi_gtfs_{run_id}.zip\"\n",
    "\n",
    "target_paths = {\n",
    "    \"routes\": f\"{raw_base_path}/routes\",\n",
    "    \"trips\": f\"{raw_base_path}/trips\",\n",
    "    \"stops\": f\"{raw_base_path}/stops\",\n",
    "    \"stop_times\": f\"{raw_base_path}/stop_times\",\n",
    "    \"calendar\": f\"{raw_base_path}/calendar\",\n",
    "    \"shapes\": f\"{raw_base_path}/shapes\",\n",
    "}\n",
    "\n",
    "required_files = {\n",
    "    \"routes\": \"routes.txt\",\n",
    "    \"trips\": \"trips.txt\",\n",
    "    \"stops\": \"stops.txt\",\n",
    "    \"stop_times\": \"stop_times.txt\",\n",
    "    \"calendar\": \"calendar.txt\",\n",
    "    \"shapes\": \"shapes.txt\",\n",
    "}\n",
    "\n",
    "delta_paths = {\n",
    "    \"routes\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_routes\",\n",
    "    \"trips\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_trips\",\n",
    "    \"stops\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_stops\",\n",
    "    \"stop_times\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_stop_times\",\n",
    "    \"calendar\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_calendar\",\n",
    "    \"shapes\": f\"abfss://{container}@{storage_account}.dfs.core.windows.net/gtfs_shapes\",\n",
    "}\n",
    "\n",
    "print(\"=== GTFS STATIC INGESTION START ===\")\n",
    "print(f\"storage_account: {storage_account}\")\n",
    "print(f\"container: {container}\")\n",
    "print(f\"ingestion_date: {ingestion_date}\")\n",
    "print(f\"raw_base_path: {raw_base_path}\")\n",
    "\n",
    "# COMMAND ----------\n",
    "def fs_exists(path: str) -> bool:\n",
    "    try:\n",
    "        dbutils.fs.ls(path)\n",
    "        return True\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "\n",
    "def file_exists(path: str) -> bool:\n",
    "    try:\n",
    "        dbutils.fs.head(path, 1)\n",
    "        return True\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "\n",
    "def ensure_local_dir(path: str) -> None:\n",
    "    if os.path.exists(path):\n",
    "        shutil.rmtree(path, ignore_errors=True)\n",
    "    os.makedirs(path, exist_ok=True)\n",
    "\n",
    "\n",
    "def cleanup_local_paths(*paths: str) -> None:\n",
    "    for path in paths:\n",
    "        try:\n",
    "            if os.path.isdir(path):\n",
    "                shutil.rmtree(path, ignore_errors=True)\n",
    "            elif os.path.isfile(path):\n",
    "                os.remove(path)\n",
    "        except Exception as e:\n",
    "            print(f\"[WARN] Falha ao limpar caminho local {path}: {e}\")\n",
    "\n",
    "\n",
    "def resolve_zip_source_path(candidate_paths):\n",
    "    print(\"Procurando ZIP GTFS nos caminhos candidatos...\")\n",
    "    for path in candidate_paths:\n",
    "        print(f\" - testando: {path}\")\n",
    "        if file_exists(path):\n",
    "            print(f\"[OK] ZIP encontrado em: {path}\")\n",
    "            return path\n",
    "    raise FileNotFoundError(\n",
    "        \"ZIP GTFS não encontrado em nenhum dos caminhos esperados:\\n\"\n",
    "        + \"\\n\".join(candidate_paths)\n",
    "    )\n",
    "\n",
    "\n",
    "def safe_count(df, name: str) -> int:\n",
    "    count = df.count()\n",
    "    print(f\"{name}: {count}\")\n",
    "    return count\n",
    "\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Validando acesso ao ADLS...\")\n",
    "root_path = f\"abfss://{container}@{storage_account}.dfs.core.windows.net/\"\n",
    "root_items = dbutils.fs.ls(root_path)\n",
    "print(f\"Acesso OK. Itens encontrados na raiz do container {container}: {len(root_items)}\")\n",
    "\n",
    "zip_source_path = resolve_zip_source_path(zip_candidate_paths)\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Preparando diretórios locais...\")\n",
    "cleanup_local_paths(zip_local_path, extract_base_local)\n",
    "ensure_local_dir(extract_base_local)\n",
    "\n",
    "print(\"Copiando ZIP do ADLS para o driver local...\")\n",
    "dbutils.fs.cp(zip_source_path, f\"file:{zip_local_path}\", True)\n",
    "print(f\"ZIP copiado para: {zip_local_path}\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Extraindo ZIP localmente...\")\n",
    "with zipfile.ZipFile(zip_local_path, \"r\") as zip_ref:\n",
    "    zip_ref.extractall(extract_base_local)\n",
    "\n",
    "extracted_files = sorted(os.listdir(extract_base_local))\n",
    "print(f\"Arquivos extraídos: {extracted_files}\")\n",
    "\n",
    "missing_files = [\n",
    "    filename for filename in required_files.values()\n",
    "    if not os.path.exists(os.path.join(extract_base_local, filename))\n",
    "]\n",
    "\n",
    "if missing_files:\n",
    "    raise FileNotFoundError(\n",
    "        f\"Arquivos obrigatórios ausentes no ZIP: {missing_files}\"\n",
    "    )\n",
    "\n",
    "print(\"Todos os arquivos obrigatórios do GTFS foram encontrados.\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Enviando arquivos extraídos para o ADLS...\")\n",
    "for entity, filename in required_files.items():\n",
    "    local_file = os.path.join(extract_base_local, filename)\n",
    "    target_dir = target_paths[entity]\n",
    "    target_file = f\"{target_dir}/{filename}\"\n",
    "\n",
    "    print(f\"Enviando {filename} -> {target_file}\")\n",
    "    dbutils.fs.cp(f\"file:{local_file}\", target_file, True)\n",
    "\n",
    "print(\"Upload dos arquivos extraídos concluído.\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Lendo arquivos GTFS do ADLS...\")\n",
    "read_options = {\n",
    "    \"header\": \"true\",\n",
    "    \"inferSchema\": \"true\",\n",
    "    \"sep\": \",\",\n",
    "}\n",
    "\n",
    "routes_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['routes']}/routes.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "trips_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['trips']}/trips.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "stops_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['stops']}/stops.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "stop_times_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['stop_times']}/stop_times.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "calendar_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['calendar']}/calendar.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "shapes_df = (\n",
    "    spark.read.options(**read_options)\n",
    "    .csv(f\"{target_paths['shapes']}/shapes.txt\")\n",
    "    .withColumn(\"ingestion_date\", lit(ingestion_date))\n",
    "    .withColumn(\"ingested_at\", current_timestamp())\n",
    "    .withColumn(\"source_file\", input_file_name())\n",
    ")\n",
    "\n",
    "print(\"Leitura dos arquivos concluída.\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Contagem de registros:\")\n",
    "safe_count(routes_df, \"routes\")\n",
    "safe_count(trips_df, \"trips\")\n",
    "safe_count(stops_df, \"stops\")\n",
    "safe_count(stop_times_df, \"stop_times\")\n",
    "safe_count(calendar_df, \"calendar\")\n",
    "safe_count(shapes_df, \"shapes\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Gravando datasets em Delta Lake...\")\n",
    "\n",
    "routes_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"routes\"])\n",
    "trips_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"trips\"])\n",
    "stops_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"stops\"])\n",
    "stop_times_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"stop_times\"])\n",
    "calendar_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"calendar\"])\n",
    "shapes_df.write.format(\"delta\").mode(\"overwrite\").save(delta_paths[\"shapes\"])\n",
    "\n",
    "print(\"Gravação em Delta concluída.\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Validando paths Delta gravados...\")\n",
    "for name, path in delta_paths.items():\n",
    "    print(f\"{name}: {'OK' if fs_exists(path) else 'NÃO ENCONTRADO'} -> {path}\")\n",
    "\n",
    "print(\"=== GTFS STATIC INGESTION END ===\")\n",
    "\n",
    "# COMMAND ----------\n",
    "print(\"Limpando arquivos temporários locais...\")\n",
    "cleanup_local_paths(zip_local_path, extract_base_local)\n",
    "print(\"Limpeza concluída.\")\n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "02_ingest_gtfs_static_data.py",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
